server:
  port: 9002

spring:
  application:
    name: auth-service

feign:
  client:
    config:
      user-service:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
jwt:
  secret: "secretkeya"
