server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev2care?currentSchema=development
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    schemas: development
    url: jdbc:postgresql://localhost:5432/dev2care
    user: postgres
    password: postgres
